fidelity/theliv

website/src/app/services/kubernetes.service.ts

changes: use new endpoint for Prometheus detect

changes: use new endpoint for Prometheus detect

---

pkg/config/config.go
pkg/config/etcd.go
pkg/database/etcd/client.go
pkg/prometheus/promclient.go
pkg/service/detector.go

load prometheus address and managednamespaces from database.

load config from db

---

alerting_rules.md
developerguide.md

developer guide for customizing prometheus alerts and investigators
Fixes #

Readme for contribution guide

---

internal/investigators/commoninvestigator.go
internal/investigators/initcontainerinvestigator.go
pkg/service/detector.go

This is the sample PR for developers/contributors's reference on investigators development.

Sample investigator

---

website/src/app/components/report-card/report-card.component.html
website/src/app/components/report-card/report-card.component.ts

fix: ui display issue

---

pkg/config/etcd.go
pkg/database/etcd/client.go

support rancher clusters and namespaces

feat: support rancher clusters and namespaces

---

pkg/auth/authmiddleware/authmiddleware.go

SAML ACS config is hardcoded
**Which issue(s) this PR fixes** 
Retrieve ACS URL from config

fix: samlacs

---

internal/investigators/common_investigator.go
pkg/err/error.go
pkg/observability/events.go
pkg/observability/k8s/k8s_event.go
pkg/prometheus/promclient.go
pkg/router/detector.go
pkg/service/detector.go
pkg/service/event.go

feat: add operation get-event

---

pkg/observability/events.go
pkg/observability/k8s/k8s_event.go
website/angular.json
website/src/app/app.component.html
website/src/app/app.module.ts
website/src/app/components/feedback/feedback.component.html
website/src/app/components/feedback/feedback.component.scss
website/src/app/components/feedback/feedback.component.spec.ts
website/src/app/components/feedback/feedback.component.ts
website/src/app/components/user-feedback/user-feedback.component.ts
website/src/app/kube-platform/kube-platform.component.html
website/src/app/kube-platform/kube-platform.component.scss
website/src/app/kube-platform/kube-platform.component.ts
website/src/app/services/kubernetes.service.ts
website/src/app/shared/util/unauthorized-interceptor.ts

This PR is UI change to display k8s events for users as a reference.
This PR also include the service change to get event type(Normal, Warning or Failed...)

feat: ui change to show k8s events

---

docs/api/adgroup.md
internal/investigators/pod_investigator.go
main.go
pkg/auth/authmiddleware/checkauth.go
pkg/router/adgroup.go
pkg/router/router.go
pkg/service/adgroup.go
pkg/service/rbac_test.go

feat: add operation add/remove cluster/namespace from ad

---

main.go
pkg/config/config.go
pkg/router/configinfo.go
website/src/app/app-routing.module.ts
website/src/app/app.component.html
website/src/app/app.component.scss
website/src/app/app.component.ts
website/src/app/app.module.ts
website/src/app/components/feedback/feedback.component.html
website/src/app/components/feedback/feedback.component.scss
website/src/app/components/feedback/feedback.component.ts
website/src/app/components/home-page/home-page.component.html
website/src/app/components/home-page/home-page.component.scss
website/src/app/components/home-page/home-page.component.spec.ts
website/src/app/components/home-page/home-page.component.ts
website/src/app/components/navigation-bar/navigation-bar.component.html
website/src/app/components/navigation-bar/navigation-bar.component.scss
website/src/app/components/navigation-bar/navigation-bar.component.ts
website/src/app/kube-platform/kube-platform.component.html
website/src/app/kube-platform/kube-platform.component.scss
website/src/app/kube-platform/kube-platform.component.ts
website/src/app/services/kubernetes.service.ts
website/src/app/shared/errors/error-dialog.component.html
website/src/app/shared/errors/error-dialog.component.scss
website/src/app/shared/util/unauthorized-interceptor.ts
website/src/index.html
website/src/styles.scss

feat: main page for UI and service change to get config info

---

website/src/app/components/home-page/home-page.component.html

fix: update video title

---

website/src/app/components/home-page/home-page.component.html
website/src/app/components/home-page/home-page.component.scss
website/src/app/components/home-page/home-page.component.ts

add loading spinner for the video

feat: UI updates for kube events

---

.github/workflows/main.yml
main.go
pkg/auth/authmiddleware/authmiddleware.go
pkg/metrics/metrics.go
pkg/router/router.go

feat: add prometheus metrics

---

website/src/app/components/feedback/feedback.component.scss
website/src/app/components/home-page/home-page.component.scss
website/src/app/components/report-card/report-card.component.html
website/src/app/kube-platform/kube-platform.component.scss
website/src/styles.scss

This fixes UI display issues when switch to dark mode. Fix input color get invisible in dark-mode.

fix: ui display for dark mode

---

pkg/auth/samlmethod/samlmethod.go

feat: refactor display name

---

internal/investigators/common.go
pkg/router/register.go
pkg/router/router.go
pkg/service/register.go

feat: cluster register api

---

.github/workflows/main.yml
go.mod
go.sum
internal/rbac/user.go
pkg/auth/authmiddleware/authmiddleware.go
pkg/auth/authmiddleware/checkauth.go
pkg/auth/localmethod/localmethod.go
pkg/auth/samlmethod/samlmethod.go
pkg/config/config.go
pkg/config/etcd.go
pkg/database/etcd/client.go

feat: fix empty displayName

---

.github/workflows/main.yml
build/Dockerfile
web/nginx/nginx.conf
web/nginx/startup.sh

fix: run as non root compliance

---

internal/investigators/common.go
internal/investigators/common_investigator.go
internal/investigators/container_crushloopbackoff_investigator.go
internal/investigators/container_imagepullbackoff_investigator.go
internal/investigators/deployment_investigator.go
internal/investigators/endpoint_investigator.go
internal/investigators/node_investigator.go
internal/investigators/pod_not_ready_investigator.go
internal/investigators/pod_pending_investigator.go
internal/problem/aggregate.go
internal/problem/problem.go
internal/problem/types.go
website/src/app/components/resource-group-content/resource-group-content.component.html
website/src/app/components/resource-group-content/resource-group-content.component.scss
website/src/app/components/resource-group-content/resource-group-content.component.ts
website/src/styles.scss

feat: UI useful cmd

---

pkg/database/etcd/client.go
pkg/service/register.go

feat: register get accountid

---

.github/workflows/main.yml
website/src/app/kube-platform/kube-platform.component.ts

fix: ui resource filter

---

build/Dockerfile
internal/investigators/pod_pending_investigator.go
web/nginx/nginx.conf
web/nginx/startup.sh

feat: support read-only filesystem
